### ISSUE TITLE
No unsubscribe available

### ISSUE THREAD

**Issue by john256474** [gliwka/bittrex-market#1]
at some point i dont need updates on some of subscribed pairs. no reason to clog my/servers' bandwidth
didnt find something relevant, so tried //marketManager.reset(); with intent to resubscribe to relevant pairs later,  but it crashed it

**Comment by gliwka** [comment]
Hi @john256474,

i've seperated your comment into two issues:
 - issue #2 covers the event you requested after the coin has been subscribed but before the whole orderbook is ready.
 - this issue covers the reset bug

I'll look into it and will keep you updated.

Kind regards,
Matthias

**Comment by LRonHubs** [comment]
Any update on closing the sockets?

**Comment by LRonHubs** [comment]
So i didnt dive too deep into the code, but if you use  the .reset() function, all you have to do is redefine a new marketManager(false) and u good

**Comment by gliwka** [comment]
Sorry, I've been quite busy lately. I'll give it a look later in the day

**Comment by gliwka** [comment]
This bug has been fixed in v2.1.3 - calling reset now truly resets the state of the MarketManager.
