### ISSUE TITLE
Expose delta order events, not just order book state

### ISSUE THREAD

**Issue by skeller88** [gliwka/bittrex-market#10]
For backtesting algorithms, this library is perfect in that it's easy to log fills along with their timestamps. However, it's also important to be able to replay updates to the order book itself. Those updates are not exposed, meaning that users of this library will have to diff snapshots of the order book if they want to reconstruct the changes to the order book that happened between timestamps. 

It looks like _updateOrderbook could be modified to emit a new event type along with the order book delta. I'll look more into this.

**Comment by skeller88** [comment]
Alright I have a PR ready. If you're interested / open to me contributing then please add me as a contributor and you can check it out and see what you think.

**Comment by gliwka** [comment]
That sounds great, it's something I didn't get around to implement yet.According to the npm stats it seems this library is picking up some traction, so every help in maintenance is greatly appreciated! 

Just submit those first changes as a pull request/patch and send me a mail to mg@cerebuild.com to establish an additional communication channel. If it all looks good, I'm more then happy to add you as contributor!

Sounds good to you?

**Comment by skeller88** [comment]
Cool! Sounds good. I'm not able to push my branch so I think you need to give me more repo permissions before I can submit a PR.

**Comment by gliwka** [comment]
Permissions are not an issue, you simply need to press the "Fork" button in the upper left corner and create a public fork repository (has to be public). Then commit the changes to your forked repository. After that you can create a pull request.

**Comment by skeller88** [comment]
Ok gotcha. I'm used to Bitbucket at my company so just diving into the world of open source now.

**Comment by gliwka** [comment]
It's merged. Thank you very much!

**Comment by skeller88** [comment]
Can you republish the npm package so that the package has the changes also?

**Comment by skeller88** [comment]
Hey, can you release the new version with the changes in this ticket? I'm
seeing the last release was on 9/13
<https://github.com/gliwka/bittrex-market/releases>.
