### ISSUE TITLE
difference between your library, and the bittrex recommended library?

### ISSUE THREAD

**Issue by amlwwalker** [gliwka/bittrex-market#25]
HI,
Your library is great, I am now using it to retrieve the most synced order book, because this library: https://github.com/dparlevliet/node.bittrex.api doesn't seem to have the ability to get an order book summary to apply the deltas to.

I was wondering if you know what the difference is, and why you are able to do this, but the one bittrex recommend using isn't? Are you using different APIs?

Thanks

**Comment by gliwka** [comment]
Hi @amlwwalker,

thank you for your interest in this library. 

The library recommended by Bittrex implements other core functionality, like the creation of orders or checking the balance. It also has support for websocket updates (https://github.com/dparlevliet/node.bittrex.api#websockets), which are the means used to transport the orderbook updates. You could use this websocket functionality and implement the orderbook yourself using this documentation: https://github.com/n0mad01/node.bittrex.api/files/1104308/WebSocketAPI_MarketTracking.docx

My library already does that for you, so you don't need to implement it yourself.

Does this answer your question?

**Comment by amlwwalker** [comment]
that does, thanks!
