### ISSUE TITLE
BuyLimit with "ConditionType"

### ISSUE THREAD

**Issue by trojanhost** [gliwka/bittrex-market#3]
i use bittrex API 1.1 and 2.0 for trading client (Delphi).
how use method BuyLimit with "ConditionType" and "Target" parameters?

this sample dont work? :

https://bittrex.com/api/v2.0/auth/market/tradebuy?&nonce=1502481723&MarketName=BTC-BCC&OrderType=LIMIT&Quantity=0.0005&Rate=0.10271362101&TimeInEffect=IMMEDIATE_OR_CANCEL&ConditionType=GREATER_THAN&Target=0.10271362101&__RequestVerificationToken=********

**Comment by gliwka** [comment]
@trojanhost Sorry, I'm not affiliated with Bittrex in any way. Please contact the Bittrex support or head over to the appropriate forum at bitcointalk.org
