### ISSUE TITLE
Error: Negotiate Unknown

### ISSUE THREAD

**Issue by LRonHubs** [gliwka/bittrex-market#4]
Receiving this error now when trying to use the lib. any fixes?

**Comment by TestniTester** [comment]
same here... and also no error hadnling if disconected?

**Comment by gliwka** [comment]
Hi,

Bittrex enabled Cloudflare to protect their website against a DDoS attack (see https://twitter.com/ramikawach/status/906184766969356289). 

Unfortunately, it's also enabled for the web socket endpoint used by this library. There's really nothing I can do right now to avoid this. Currently, it's only possible to access this endpoint using the browser.

Best,
Matthias

**Comment by gliwka** [comment]
@TestniTester The current error handling tries to reconnect and replay the missed trades / data. But thats currently not possible, since the endpoint is not available at the moment.

**Comment by gliwka** [comment]
I'll contact the Bittrex support and try to work something out.

**Comment by gliwka** [comment]
Seems like nothing changed on the cloudflare side. No response from the support yet. I'll implement cloud scraper to circumvent the DDoS protection. This should fix the error.

**Comment by gliwka** [comment]
@LRonHubs @TestniTester Please update to v2.1.2.

It fixed the issue.
