### ISSUE TITLE
disconnect ? unsubscribe?

### ISSUE THREAD

**Issue by TestniTester** [gliwka/bittrex-market#5]
hi,
im looking for a way to disconnect from bittrex feed
AND
how can in unsubscribe from feed already subscribed to?

**Comment by gliwka** [comment]
Hi @TestniTester,

to disconnect from the feed make sure to update bittrex-market to the latest version. Then just call the reset method on the MarketManager. (```marketManager.reset()```). After this you can reconnect and subscribe to the currency pairs of interest.

Theres currently no way to unsubscribe from a single currency pair available in the Bittrex Websocket API. The only way is to reset/close the whole connection.

Best,
Matthias

**Comment by TestniTester** [comment]
Thank you !
