### ISSUE TITLE
marketManager stopped working!?

### ISSUE THREAD

**Issue by TestniTester** [gliwka/bittrex-market#7]
hi!
it worked like yesterday?
today i get error:
Error: "value" required in setHeader("cookie", value)

copy/paste of example here

**Comment by gliwka** [comment]
Hi,

Bittrex disabled cloudflare again. I've added a check so the library works with and without cloud flare.

Please update to version 2.1.4.

Best,
Matthias

**Comment by TestniTester** [comment]
Thank you!
but 
makretManager.stop()
or
makretManager.close()
give me error?
how can i disconnect the mannager or better said.. disconnect the bittrex feed ?

**Comment by gliwka** [comment]
marketManager.reset() should do what you want.

**Comment by TestniTester** [comment]
marketManager.reset() 
throws error and brakes

**Comment by gliwka** [comment]
Can you post the error here?

**Comment by TestniTester** [comment]
![image](https://user-images.githubusercontent.com/29655426/30372350-d0bf3b80-987d-11e7-9ed9-6f6a8103546e.png)

**Comment by gliwka** [comment]
Thanks. I'll roll out a fix for this race condition later in the evening.

**Comment by gliwka** [comment]
Sorry for the delay, I'll try to get it sorted out today.

**Comment by gliwka** [comment]
Duplicate of #20 - will continue to fix the error in that issue.
